"""Validate NSM Layer C: does pramāṇa ascertainment predict ALM correctness?

Runs the instruction-tuned ALM on the held-out `transcribe` task, decoding each clip with a per-token
confidence (mean max-softmax probability). Layer C (gold-free) labels each output ASCERTAINED or not.
We then compare the CER of ascertained vs rejected outputs: if Layer C is a real epistemic filter,
ascertained transcriptions are measurably more accurate. Run in prabhasa/nemo-gb10.

    python scripts/nsm/validate_layer_c.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

from pranava.alm.core_adapter import SanskritCore
from pranava.alm.instruct import EOS, build_prefix
from pranava.alm.lora import inject_lora
from pranava.alm.projector import SphotaProjector
from pranava.alm.train import _levenshtein
from pranava.nsm.layer_c import validate_output
from pranava.pramana_layer.auditor import Verdict

ROOT = Path("/work/pranava") if Path("/work/pranava").exists() else Path(__file__).resolve().parents[2]
FEATS = ROOT / "data/alm/speech_corpus_multi/feats"
CORPUS = ROOT / "data/alm/instruct_corpus/manifest.jsonl"


def _feat(wav, dev):
    return torch.from_numpy(np.load(FEATS / f"{Path(wav).stem}.npy").astype(np.float32)).unsqueeze(0).to(dev)


@torch.no_grad()
def _decode_with_conf(core, prefix, max_new=64):
    """Greedy decode + mean per-token confidence (max softmax prob over generated bytes)."""
    x = prefix
    out, probs = [], []
    for _ in range(max_new):
        logits = core.forward_embeds(x)[0, -1]
        p = F.softmax(logits, dim=-1)
        nxt = int(torch.argmax(p).item())
        if nxt == EOS:
            break
        out.append(nxt); probs.append(float(p[nxt].item()))
        x = torch.cat([x, core.model.embed(torch.tensor([[nxt]], device=core.torch_device))], dim=1)
    text = bytes(b for b in out if 9 <= b < 127).decode("latin-1", "ignore").strip()
    conf = float(np.mean(probs)) if probs else 0.0
    return text, conf


def _cer(pred: str, gold: str) -> float:
    p, g = list(pred.encode()), list(gold.encode())
    return _levenshtein(p, g) / max(1, len(g))


def main() -> int:
    core = SanskritCore(arm="m2", device="cuda").load()
    for p in core.model.parameters():
        p.requires_grad_(False)
    dev, bias = core.torch_device, core.structural_bias
    inject_lora(core.model, r=8, alpha=16); core.model.to(dev)
    d_enc = int(np.load(next(FEATS.glob("*.npy"))).shape[-1])
    proj = SphotaProjector(d_enc=d_enc, d_model=core.d_model, downsample=4).to(dev)
    blob = torch.load(ROOT / "data/alm/instruct_ckpt.pt", map_location=dev, weights_only=True)
    proj.load_state_dict(blob["projector"])
    lsd = {n: p for n, p in core.model.named_parameters() if ".A" in n or ".B" in n}
    for n, w in blob["lora"].items():
        if n in lsd:
            lsd[n].data.copy_(w.to(dev))
    proj.eval()

    # Test the real question on tasks with genuine correctness variance (the extractive kāraka +
    # language tasks the model gets sometimes-right/sometimes-wrong). A confidence filter can only be
    # validated where there is a correct/incorrect split to separate — `transcribe` is uniformly poor
    # (mixing English the Sanskrit core cannot transcribe), so it carries no signal to detect.
    val = [r for r in (json.loads(l) for l in CORPUS.open())
           if r["split"] == "val" and r["task"] != "transcribe"]
    asc_correct, rej_correct = [], []
    records = []
    for ex in val:
        audio = proj(_feat(ex["wav"], dev), structural_bias=bias)
        text, conf = _decode_with_conf(core, build_prefix(core, audio, ex["instruction"]))
        rep = validate_output(text, conf)
        correct = int(text == ex["response"])  # exact-match: the task has real right/wrong variance
        (asc_correct if rep.verdict is Verdict.ASCERTAINED else rej_correct).append(correct)
        records.append({"task": ex["task"], "gold": ex["response"], "pred": text,
                        "conf": round(conf, 3), "verdict": rep.verdict.value, "correct": correct,
                        "cer_transcribe_ref": round(_cer(text, ex["response"]), 3)})

    acc = lambda xs: round(float(np.mean(xs)), 4) if xs else None
    a_acc, r_acc = acc(asc_correct), acc(rej_correct)
    both = asc_correct and rej_correct
    out = {
        "task": "instruction tasks with correctness variance (held-out, excl. transcribe)",
        "n": len(val), "n_ascertained": len(asc_correct), "n_rejected": len(rej_correct),
        "accuracy_ascertained": a_acc, "accuracy_rejected": r_acc,
        "layer_c_predicts_correctness": bool(both and a_acc > r_acc),
        "accuracy_gap": round(a_acc - r_acc, 4) if both else None,
        "reward": "gold-free: pratyakṣa(confidence) + śabda(legality) + anumāna(non-repetition)",
    }
    (ROOT / "data/alm/layer_c_validation.json").write_text(json.dumps(out, indent=2, ensure_ascii=False))
    (ROOT / "data/alm/layer_c_records.json").write_text(json.dumps(records, indent=2, ensure_ascii=False))
    print(json.dumps(out, indent=2, ensure_ascii=False), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
